version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  ibmmq:
    image: ibmcom/mq
    hostname: mq-1
    container_name: mq-1
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
    ports:
      - 1414:1414
      - 9443:9443
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "35SeU+<3h~h4e7k"
      ACCEPT_EULA: "Y"
  kafka:
    build: .
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.8.107
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "message-in-V1:1:3,message-out-V1:1:3:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
